#!/usr/bin/env bash

set -euo pipefail

readonly TARGET_TAG="${1:?usage: deploy_ghcr_release.sh sha-<commit>}"
readonly IMAGE_PREFIX="${IMAGE_PREFIX:-ghcr.io/temu-f4/runners-feed}"
readonly ENV_FILE="${RUNNERS_FEED_ENV_FILE:-/etc/runners-feed/prod.env}"
readonly BASE_URL="${PRODUCTION_BASE_URL:-https://140.238.0.197}"
readonly STATE_DIR="${RUNNERS_FEED_DEPLOY_STATE_DIR:-/var/lib/runners-feed-cd}"
readonly STATE_FILE="${STATE_DIR}/last-successful.env"
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
readonly PROJECT_ROOT
readonly RELEASE_VERIFIER="${RELEASE_VERIFIER:-${PROJECT_ROOT}/deploy/verify_release.sh}"
readonly COMPOSE_FILES=(
  -f "${PROJECT_ROOT}/compose.yaml"
  -f "${PROJECT_ROOT}/compose.coach.yaml"
)
readonly SERVICES=(api frontend web coach-worker maintenance)
readonly SUPPORT_SERVICES=(alertmanager)

export IMAGE_PREFIX

if [[ ! "${TARGET_TAG}" =~ ^sha-[0-9a-f]{40}$ ]]; then
  echo "Refusing non-immutable image tag: ${TARGET_TAG}" >&2
  exit 2
fi

if [[ ! -r "${ENV_FILE}" ]]; then
  echo "Production environment file is not readable: ${ENV_FILE}" >&2
  exit 2
fi

if [[ ! -r "${RELEASE_VERIFIER}" ]]; then
  echo "Release verifier is not readable: ${RELEASE_VERIFIER}" >&2
  exit 2
fi

mkdir -p "${STATE_DIR}"

compose() {
  docker compose \
    --env-file "${ENV_FILE}" \
    --project-name runners-feed \
    "${COMPOSE_FILES[@]}" \
    --profile coach \
    "$@"
}

verify_release() {
  local target_tag="$1"

  env \
    IMAGE_PREFIX="${IMAGE_PREFIX}" \
    PRODUCTION_BASE_URL="${BASE_URL}" \
    RUNNERS_FEED_ENV_FILE="${ENV_FILE}" \
    RUNNERS_FEED_PROJECT_DIR="${PROJECT_ROOT}" \
    RUNNERS_FEED_DEPLOY_STATE_DIR="${STATE_DIR}" \
    bash "${RELEASE_VERIFIER}" "${target_tag}"
}

deploy_tag() {
  IMAGE_TAG="$1"
  export IMAGE_TAG

  compose config --quiet || return 1
  compose pull "${SERVICES[@]}" "${SUPPORT_SERVICES[@]}" || return 1
  compose up \
    --detach \
    --no-build \
    --no-deps \
    --wait \
    --wait-timeout 180 \
    "${SERVICES[@]}" "${SUPPORT_SERVICES[@]}" || return 1
  verify_release "$1" || return 1
}

previous_tag=""
if [[ -r "${STATE_FILE}" ]]; then
  # The state file is generated by this script and contains only IMAGE_TAG.
  previous_tag="$(sed -n 's/^IMAGE_TAG=//p' "${STATE_FILE}" | head -n 1)"
fi

echo "Deploying ${TARGET_TAG}"
if deploy_tag "${TARGET_TAG}"; then
  temporary_state="$(mktemp "${STATE_DIR}/last-successful.XXXXXX")"
  printf 'IMAGE_TAG=%s\n' "${TARGET_TAG}" >"${temporary_state}"
  chmod 0640 "${temporary_state}"
  mv "${temporary_state}" "${STATE_FILE}"
  echo "Deployment succeeded: ${TARGET_TAG}"
  exit 0
fi

echo "Deployment failed: ${TARGET_TAG}" >&2
IMAGE_TAG="${TARGET_TAG}"
compose logs --no-color --tail 150 "${SERVICES[@]}" "${SUPPORT_SERVICES[@]}" || true

if [[ "${previous_tag}" =~ ^sha-[0-9a-f]{40}$ ]] && [[ "${previous_tag}" != "${TARGET_TAG}" ]]; then
  echo "Rolling back to ${previous_tag}" >&2
  if deploy_tag "${previous_tag}"; then
    echo "Rollback succeeded: ${previous_tag}" >&2
  else
    echo "Rollback failed: ${previous_tag}" >&2
  fi
else
  echo "No previous immutable release is available for rollback" >&2
fi

exit 1
