FROM python:3.11-slim-bookworm

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1

WORKDIR /app

COPY requirements.celery.txt .

RUN pip install --upgrade pip \
    && pip install -r requirements.celery.txt

COPY celery_app.py .
COPY tasks.py .

CMD ["celery", "-A", "celery_app:celery_app", "worker", "--loglevel=INFO", "--concurrency=1"]
